/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Home Component'])),
    (l()(),import0.ɵted((null as any),['\n        ']))
  ]
  ,(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-home',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import0.ɵdid(57344,(null as any),0,import1.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const HomeComponentNgFactory:import0.ComponentFactory<import1.HomeComponent> = import0.ɵccf('app-home',import1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovV2ViL2RlbW9zL0FuZ3VsYXI0L2N1c3RvbS13b3JrZmxvdy9zcmMvYXBwL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Y6L1dlYi9kZW1vcy9Bbmd1bGFyNC9jdXN0b20td29ya2Zsb3cvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL0Y6L1dlYi9kZW1vcy9Bbmd1bGFyNC9jdXN0b20td29ya2Zsb3cvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9GOi9XZWIvZGVtb3MvQW5ndWxhcjQvY3VzdG9tLXdvcmtmbG93L3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8aDE+SG9tZSBDb21wb25lbnQ8L2gxPlxuICAgICAgICAiLCI8YXBwLWhvbWU+PC9hcHAtaG9tZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7SUFDUTtJQUFJO0lBQW1COzs7Ozs7SUNEL0I7Z0JBQUE7OztJQUFBOzs7In0=
