/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './users.component';
const styles_UsersComponent:any[] = ([] as any[]);
export const RenderType_UsersComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UsersComponent,
  data: {}
}
);
export function View_UsersComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Users Component'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(null as any));
}
function View_UsersComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'app-users',([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,RenderType_UsersComponent)),
    import0.ɵdid(57344,(null as any),0,import1.UsersComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const UsersComponentNgFactory:import0.ComponentFactory<import1.UsersComponent> = import0.ɵccf('app-users',import1.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRjovV2ViL2RlbW9zL0FuZ3VsYXI0L2N1c3RvbS13b3JrZmxvdy9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9GOi9XZWIvZGVtb3MvQW5ndWxhcjQvY3VzdG9tLXdvcmtmbG93L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzIiwibmc6Ly8vRjovV2ViL2RlbW9zL0FuZ3VsYXI0L2N1c3RvbS13b3JrZmxvdy9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vRjovV2ViL2RlbW9zL0FuZ3VsYXI0L2N1c3RvbS13b3JrZmxvdy9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cy5Vc2Vyc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Vc2VycyBDb21wb25lbnQ8L2gxPlxyXG4iLCI8YXBwLXVzZXJzPjwvYXBwLXVzZXJzPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJO0lBQW9COzs7Ozs7SUNBeEI7Z0JBQUE7OztJQUFBOzs7In0=
